# Memory Configuration
RAM_ADDRESS_BITS = 8
RAM_CONTENT_BITS = 16
ROM_ADDRESS_BITS = RAM_ADDRESS_BITS

# CPU Configuration
COMPUTER_WORD_BITS = 15
INSTRUCTION_CODE_BITS = 4
REGISTER_ADDRESS_BITS = 3
REGISTER_CONTENT_BITS = 16
