[project]
name = "cpu-emulator"
version = "0.1.0"
description = "CPU Emulator by Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
