# clock
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports {clk}]

## 7-seg segments (active-low)
# seg[0]=CA, seg[1]=CB, seg[2]=CC, seg[3]=CD, seg[4]=CE, seg[5]=CF, seg[6]=CG
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]

## decimal point (active-low)
set_property PACKAGE_PIN V7 [get_ports {decimal_point}]
set_property IOSTANDARD LVCMOS33 [get_ports {decimal_point}]

## anodes (active-low)  an[0]=右端桁 → an[3]=左端桁
set_property PACKAGE_PIN U2 [get_ports {anode_digit[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_digit[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_digit[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode_digit[*]}]


# input (16bits toggle switch)
set_property PACKAGE_PIN V17 [get_ports {input[0]}]
set_property PACKAGE_PIN V16 [get_ports {input[1]}]
set_property PACKAGE_PIN W16 [get_ports {input[2]}]
set_property PACKAGE_PIN W17 [get_ports {input[3]}]
set_property PACKAGE_PIN W15 [get_ports {input[4]}]
set_property PACKAGE_PIN V15 [get_ports {input[5]}]
set_property PACKAGE_PIN W14 [get_ports {input[6]}]
set_property PACKAGE_PIN W13 [get_ports {input[7]}]
set_property PACKAGE_PIN V2 [get_ports {input[8]}]
set_property PACKAGE_PIN T3 [get_ports {input[9]}]
set_property PACKAGE_PIN T2 [get_ports {input[10]}]
set_property PACKAGE_PIN R3 [get_ports {input[11]}]
set_property PACKAGE_PIN W2 [get_ports {input[12]}]
set_property PACKAGE_PIN U1 [get_ports {input[13]}]
set_property PACKAGE_PIN T1 [get_ports {input[14]}]
set_property PACKAGE_PIN R2 [get_ports {input[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input[*]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3  [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3  [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3  [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3  [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3  [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1  [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1  [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
